using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace CoreWebApiSuperHero.Data.Config
{
    public class DepartmentConfig : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> builder)
        {
            builder.ToTable("Departments"); // This specifies the table name for the Student entity in the database

            builder.HasKey(s => s.DepartmentId);//prry key is automatically configured by EF Core
            builder.Property(s => s.DepartmentId).UseIdentityColumn();// This sets the Id property to be an identity column, meaning it will be automatically generated by the database

            builder.Property(s => s.DepartmentName).IsRequired().HasMaxLength(250); // This sets the StudentName property to be required and have a maximum length of 50 characters

            builder.Property(s => s.Description).IsRequired(false).HasMaxLength(500);
           
            builder.HasData(new List<Department>()
            {
                new Department
                {
                    DepartmentId = 1,
                    DepartmentName = "ECS",
                    Description = "Engineering Computer Science"

                },
                new Department
                {
                    DepartmentId = 2,
                    DepartmentName = "CES",
                    Description = "Computer Engineering Science"
                }
            });

        }
    }
}
