using CoreWebApiSuperHero.Data;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CoreWebApiSuperHero.Data.Config
{
    public class RoleConfig:IEntityTypeConfiguration<Role>
    {
         public void Configure(EntityTypeBuilder<Role> builder)
         {
            builder.ToTable("Roles"); // This specifies the table name for the Student entity in the database

            builder.HasKey(s => s.RoleId);//prry key is automatically configured by EF Core
            builder.Property(s => s.RoleId).UseIdentityColumn();// This sets the Id property to be an identity column, meaning it will be automatically generated by the database

            builder.Property(s => s.RoleName).IsRequired().HasMaxLength(250); // This sets the StudentName property to be required and have a maximum length of 50 characters

            builder.Property(s => s.Description).IsRequired(false);

            builder.Property(s => s.IsDeleated).IsRequired();

            builder.Property(s => s.IsActive).IsRequired();

            builder.Property(s => s.Createdate).IsRequired();

            builder.Property(s => s.Updatedate).IsRequired();
        }
    }
}
