namespace CoreWebApiSuperHero.Data.Config;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

public class UserConfig : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users"); // This specifies the table name for the Student entity in the database

        builder.HasKey(s => s.UserId);//prry key is automatically configured by EF Core
        builder.Property(s => s.UserId).UseIdentityColumn();// This sets the Id property to be an identity column, meaning it will be automatically generated by the database

        builder.Property(s => s.UserName).IsRequired().HasMaxLength(50); // This sets the StudentName property to be required and have a maximum length of 50 characters

        builder.Property(s => s.Password).IsRequired();

        builder.Property(s => s.PasswordSalt).IsRequired();
        builder.Property(s => s.IsDeleated).IsRequired();
        builder.Property(s => s.IsActive).IsRequired();
        builder.Property(s => s.Createdate).IsRequired();
        builder.Property(s => s.UserType).IsRequired();        
    }
}

