using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreWebApiSuperHero.Data
{
    public class Student
    {
        [Key] // This attribute is used to specify that the Id property is the primary key of the Student entity
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // This attribute is used to specify that the Id property is an identity column in the database, meaning it will be automatically generated by the database

        public int Id { get; set; }

        // [Required(ErrorMessage = "Student name is required.")]
        // [StringLength(50, ErrorMessage = "Hero name cannot be longer than 30 characters.")]// This attribute is used to specify that the Name property is required and cannot be longer than 100 characters
        public string StudentName { get; set; } = string.Empty;

        // [EmailAddress(ErrorMessage = "Invalid email address.")]
        public string? Email { get; set; } // This property is not decorated with any attributes, so it is optional and can be null or empty
        public string? Address { get; set; }

        //[ValidateNever] // This attribute is used to prevent validation of this property in ASP.NET Core MVC
        public DateTime? DOB { get; set; }

       // public int? DepartmentId { get; set; }
       // public virtual Department? Department { get; set; }
    }
}
